"""S7: regenerate the README "Measured results" section from results/v0.1.0a1.json.

No measured number is hand-written. This replaces everything between the
``## Measured results`` heading and the next ``## `` heading with a generated block, then
verifies the README contains no stray ``<!--MEASURED@S6-->`` marker. Run with --check in CI to
fail if the README is out of sync with the results file.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
RESULTS = ROOT / "results" / "v0.1.0a1.json"
README = ROOT / "README.md"
HEADING = "## Measured results"


def _block() -> str:
    data = json.loads(RESULTS.read_text(encoding="utf-8"))
    m = data["metrics"]
    lines = [
        HEADING,
        "",
        f"Generated by `scripts/gen_readme_numbers.py` from `results/v0.1.0a1.json` "
        f"(demoforge {data['version']}, `mode={data['mode']}`, {data['robot']}, "
        f"{data['dataset_n']} episodes, {data['os']}/{data['python']}, {data['date']}).",
        "",
        f"> {data['disclaimer']}",
        "",
        "| quantity | before | after |",
        "|---|---|---|",
        f"| dynamic limit violations (vel/acc/jerk samples) | {m['limit_violations_before']} "
        f"| {m['limit_violations_after']} |",
        f"| position-box violations (re-timing cannot change these) "
        f"| {m['position_violations_before']} | {m['position_violations_after']} |",
        f"| max \\|jerk\\| (rad/s³) | {m['max_jerk_before']} | {m['max_jerk_after']} |",
        "",
        f"- Path deviation (max joint-space, keep_count mode): **{m['path_deviation_max']}** "
        "(positions are preserved exactly; this is 0 by construction in keep_count).",
        f"- Deterministic (bit-exact across reruns): **{m['determinism_bit_exact']}**.",
        f"- Contact/dwell segments flagged and pace-preserved: **{m['contact_segments_flagged']}**.",
        "",
    ]
    return "\n".join(lines)


def _rewrite(text: str, block: str) -> str:
    lines = text.splitlines()
    start = next((i for i, ln in enumerate(lines) if ln.strip() == HEADING), None)
    if start is None:
        raise SystemExit(f"README has no {HEADING!r} heading")
    end = next((i for i in range(start + 1, len(lines)) if lines[i].startswith("## ")), len(lines))
    return "\n".join(lines[:start] + block.splitlines() + [""] + lines[end:]).rstrip() + "\n"


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="fail if README is out of sync")
    args = ap.parse_args()

    block = _block()
    current = README.read_text(encoding="utf-8")
    updated = _rewrite(current, block)

    if args.check:
        if current != updated:
            raise SystemExit("README 'Measured results' is out of sync; run gen_readme_numbers.py")
        if "<!--MEASURED@S6-->" in current:
            raise SystemExit("README still has the <!--MEASURED@S6--> placeholder marker")
        print("README numbers in sync with results/v0.1.0a1.json")
        return

    README.write_text(updated, encoding="utf-8")
    print(f"README 'Measured results' regenerated from {RESULTS.name}")


if __name__ == "__main__":
    main()
